import time

dog=("Doggywoggy\n")
name = input("Phwatt naam : ")
time.sleep(5)
print("I see, aaa! ")
time.sleep(4)
print("Cod name that " + name)
time.sleep(5)
print("I will call you " + dog)
time.sleep(3)
numby=input("Phwat numby there? " + dog +'\n>' )
time.sleep(4)
print("aaa!")
time.sleep(4)
print("\nStupey numby that, " + numby + " there " + dog)
time.sleep(4)
print("Bye byes, there " + dog)
time.sleep(2)
